export interface Question {
  id: number
  question: string
  options: string[]
  correctIndex: number
  explanation: string
}

export interface Assignment {
  id: string
  title: string
  course: string
  icon: string
  dueDate: string
  durationMins: number
  totalQuestions: number
  completedQuestions: number
  status: "pending" | "in-progress" | "completed" | "overdue"
  points: number
  questions: Question[]
}

export const assignments: Assignment[] = [
  {
    id: "1",
    title: "Python Basics Assessment",
    course: "Python",
    icon: "🐍",
    dueDate: "Mar 10, 2026",
    durationMins: 30,
    totalQuestions: 20,
    completedQuestions: 20,
    status: "completed",
    points: 100,
    questions: [
      {
        id: 1,
        question: "What will `print(type(42))` output?",
        options: ["<class 'int'>", "<class 'number'>", "<class 'integer'>", "<type 'int'>"],
        correctIndex: 0,
        explanation: "In Python 3, type() returns the class type. For integer 42, it returns <class 'int'>.",
      },
      {
        id: 2,
        question: "Which of the following is a valid Python variable name?",
        options: ["2myVar", "my-var", "_myVar", "my var"],
        correctIndex: 2,
        explanation: "Variable names can start with underscore or a letter, but not a digit or hyphen. Spaces are not allowed.",
      },
      {
        id: 3,
        question: "What does the `//` operator do in Python?",
        options: ["Regular division", "Floor division", "Power", "Modulo"],
        correctIndex: 1,
        explanation: "// is the floor division operator — it divides and rounds down to the nearest integer. E.g., 7 // 2 = 3.",
      },
      {
        id: 4,
        question: "How do you create a multi-line string in Python?",
        options: ["Using single quotes 'text'", "Using double quotes \"text\"", "Using triple quotes \"\"\"text\"\"\"", "Using backslash \\n"],
        correctIndex: 2,
        explanation: "Triple quotes (\"\"\" or ''') allow strings to span multiple lines including newlines literally.",
      },
      {
        id: 5,
        question: "What is the output of `len([1, 2, 3, [4, 5]])`?",
        options: ["5", "4", "3", "Error"],
        correctIndex: 1,
        explanation: "len() counts top-level elements. The list has 4 elements: 1, 2, 3, and [4, 5] as a single nested list.",
      },
      {
        id: 6,
        question: "Which method removes and returns the last element of a list?",
        options: ["remove()", "delete()", "pop()", "discard()"],
        correctIndex: 2,
        explanation: "list.pop() removes and returns the last element by default. You can also pass an index: list.pop(0).",
      },
      {
        id: 7,
        question: "What is a tuple in Python?",
        options: [
          "A mutable ordered sequence",
          "An immutable ordered sequence",
          "An unordered key-value store",
          "A mutable unordered collection",
        ],
        correctIndex: 1,
        explanation: "Tuples are immutable (cannot be changed after creation) and ordered. They use () syntax.",
      },
      {
        id: 8,
        question: "What does `range(2, 10, 3)` produce?",
        options: ["[2, 5, 8]", "[2, 4, 6, 8]", "[2, 5, 8, 11]", "[3, 6, 9]"],
        correctIndex: 0,
        explanation: "range(start, stop, step) produces: 2, 5, 8. It starts at 2, increments by 3, and stops before 10.",
      },
      {
        id: 9,
        question: "Which keyword is used to define a function in Python?",
        options: ["function", "func", "def", "define"],
        correctIndex: 2,
        explanation: "The 'def' keyword defines a function in Python: def my_function():.",
      },
      {
        id: 10,
        question: "What is the output of `'hello'[1:4]`?",
        options: ["hell", "ell", "ello", "hel"],
        correctIndex: 1,
        explanation: "Slicing [1:4] extracts characters at index 1, 2, 3 (not 4). 'hello'[1] = 'e', [2] = 'l', [3] = 'l' → 'ell'.",
      },
      {
        id: 11,
        question: "How do you check if a key exists in a dictionary?",
        options: ["dict.has(key)", "key in dict", "dict.contains(key)", "dict.exists(key)"],
        correctIndex: 1,
        explanation: "The 'in' operator checks for key existence: 'key' in my_dict returns True/False.",
      },
      {
        id: 12,
        question: "What is a list comprehension?",
        options: [
          "A way to import lists from other files",
          "A compact syntax to create lists from iterables",
          "A method to sort lists",
          "A function that returns a list",
        ],
        correctIndex: 1,
        explanation: "List comprehensions: [expr for item in iterable if condition]. E.g., [x*2 for x in range(5)].",
      },
      {
        id: 13,
        question: "What does `*args` in a function signature mean?",
        options: [
          "A required argument named args",
          "A pointer to a variable",
          "Accepts any number of positional arguments as a tuple",
          "Accepts any number of keyword arguments as a dict",
        ],
        correctIndex: 2,
        explanation: "*args collects extra positional arguments into a tuple inside the function.",
      },
      {
        id: 14,
        question: "Which of these is NOT a Python built-in data type?",
        options: ["dict", "set", "array", "tuple"],
        correctIndex: 2,
        explanation: "array is not a built-in type. Python has list, dict, tuple, set. Arrays come from the 'array' module or NumPy.",
      },
      {
        id: 15,
        question: "What is the result of `bool('')`?",
        options: ["True", "False", "None", "Error"],
        correctIndex: 1,
        explanation: "Empty string is falsy in Python. bool('') returns False. Any non-empty string is True.",
      },
      {
        id: 16,
        question: "How do you open a file for reading in Python?",
        options: ["open('file', 'w')", "open('file', 'r')", "open('file', 'a')", "open('file', 'x')"],
        correctIndex: 1,
        explanation: "'r' mode opens a file for reading. 'w' writes (overwrites), 'a' appends, 'x' creates a new file.",
      },
      {
        id: 17,
        question: "What does the `pass` statement do?",
        options: [
          "Exits a loop",
          "Skips the current iteration",
          "Does nothing — acts as a placeholder",
          "Passes a value to the caller",
        ],
        correctIndex: 2,
        explanation: "pass is a no-operation statement used as a placeholder where syntax requires a statement but no code is needed yet.",
      },
      {
        id: 18,
        question: "What is the difference between `is` and `==` in Python?",
        options: [
          "No difference",
          "== checks value equality; is checks identity (same object in memory)",
          "is checks value equality; == checks type equality",
          "== is faster than is",
        ],
        correctIndex: 1,
        explanation: "== compares values. 'is' checks if two variables point to the exact same object in memory.",
      },
      {
        id: 19,
        question: "Which exception handles division by zero?",
        options: ["ValueError", "TypeError", "ZeroDivisionError", "ArithmeticError"],
        correctIndex: 2,
        explanation: "ZeroDivisionError is raised when dividing by zero. ArithmeticError is its parent class.",
      },
      {
        id: 20,
        question: "What does `enumerate(['a', 'b', 'c'])` return?",
        options: [
          "[(0, 'a'), (1, 'b'), (2, 'c')]",
          "['a', 'b', 'c']",
          "{0: 'a', 1: 'b', 2: 'c'}",
          "(0, 1, 2)",
        ],
        correctIndex: 0,
        explanation: "enumerate() returns an iterator of (index, value) pairs, which unpack to tuples like (0, 'a').",
      },
    ],
  },
  {
    id: "2",
    title: "SQL Joins Practice",
    course: "SQL",
    icon: "🗄️",
    dueDate: "Mar 12, 2026",
    durationMins: 25,
    totalQuestions: 15,
    completedQuestions: 8,
    status: "in-progress",
    points: 75,
    questions: [
      {
        id: 1,
        question: "Which JOIN returns all rows from both tables, with NULLs where there is no match?",
        options: ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"],
        correctIndex: 2,
        explanation: "FULL OUTER JOIN returns all rows from both tables. Non-matching rows get NULL for the other table's columns.",
      },
      {
        id: 2,
        question: "What does a LEFT JOIN return?",
        options: [
          "Only matching rows",
          "All rows from the left table, matched rows from the right (NULLs if no match)",
          "All rows from the right table",
          "All rows from both tables",
        ],
        correctIndex: 1,
        explanation: "LEFT JOIN keeps all rows from the left table. If no match in the right table, those columns are NULL.",
      },
      {
        id: 3,
        question: "What is the purpose of the ON clause in a JOIN?",
        options: [
          "To filter results after joining",
          "To specify the join condition between tables",
          "To select specific columns",
          "To order results",
        ],
        correctIndex: 1,
        explanation: "ON specifies how to match rows between tables, e.g., ON employees.dept_id = departments.id.",
      },
      {
        id: 4,
        question: "Which SQL clause is used to filter results AFTER grouping?",
        options: ["WHERE", "HAVING", "FILTER", "GROUP FILTER"],
        correctIndex: 1,
        explanation: "HAVING filters groups after GROUP BY. WHERE filters rows before grouping. HAVING can use aggregate functions.",
      },
      {
        id: 5,
        question: "What does `SELECT COUNT(*) FROM orders WHERE status = 'paid'` return?",
        options: [
          "All paid orders",
          "The number of paid orders",
          "The sum of paid order amounts",
          "The first paid order",
        ],
        correctIndex: 1,
        explanation: "COUNT(*) counts rows. Combined with WHERE status='paid', it counts only the rows matching that condition.",
      },
      {
        id: 6,
        question: "What is a self-join?",
        options: [
          "Joining a table to itself",
          "A join with no ON condition",
          "Joining primary keys together",
          "A join that creates a new table",
        ],
        correctIndex: 0,
        explanation: "A self-join joins a table to itself using aliases. Useful for hierarchical data like employees and managers.",
      },
      {
        id: 7,
        question: "Which join type is equivalent to INNER JOIN?",
        options: ["LEFT JOIN", "OUTER JOIN", "JOIN (without qualifier)", "NATURAL JOIN"],
        correctIndex: 2,
        explanation: "JOIN without any qualifier defaults to INNER JOIN — only returning rows with matches in both tables.",
      },
      {
        id: 8,
        question: "What does CROSS JOIN produce?",
        options: [
          "Only matching rows",
          "All rows from the left table",
          "The Cartesian product of both tables",
          "Rows with NULL values removed",
        ],
        correctIndex: 2,
        explanation: "CROSS JOIN produces every combination of rows from both tables. If A has 3 rows and B has 4, the result has 12 rows.",
      },
      {
        id: 9,
        question: "In SQL, what does NULL represent?",
        options: ["Zero", "Empty string", "Absence of a value", "False"],
        correctIndex: 2,
        explanation: "NULL means the value is unknown or absent — not zero, not empty string. Use IS NULL (not = NULL) to check.",
      },
      {
        id: 10,
        question: "Which aggregate function returns the highest value in a column?",
        options: ["TOP()", "MAXIMUM()", "MAX()", "HIGHEST()"],
        correctIndex: 2,
        explanation: "MAX() returns the maximum value. MIN() returns the minimum. Both ignore NULL values.",
      },
      {
        id: 11,
        question: "What does the DISTINCT keyword do?",
        options: [
          "Sorts results",
          "Removes duplicate rows from the result",
          "Filters NULL values",
          "Speeds up queries",
        ],
        correctIndex: 1,
        explanation: "SELECT DISTINCT removes duplicate rows. E.g., SELECT DISTINCT city FROM customers returns each city once.",
      },
      {
        id: 12,
        question: "Which of these correctly finds students with no enrolled courses (using a subquery)?",
        options: [
          "SELECT * FROM students WHERE id NOT IN (SELECT student_id FROM enrollments)",
          "SELECT * FROM students WHERE courses = NULL",
          "SELECT * FROM students LEFT JOIN enrollments ON id = student_id WHERE id = NULL",
          "SELECT * FROM students WHERE NOT courses",
        ],
        correctIndex: 0,
        explanation: "NOT IN with a subquery finds students whose IDs don't appear in the enrollments table — i.e., unenrolled students.",
      },
      {
        id: 13,
        question: "What is the correct order of SQL clauses?",
        options: [
          "SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY",
          "FROM → SELECT → WHERE → ORDER BY → GROUP BY → HAVING",
          "SELECT → WHERE → FROM → GROUP BY → ORDER BY",
          "FROM → WHERE → SELECT → HAVING → GROUP BY",
        ],
        correctIndex: 0,
        explanation: "The logical order is SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY — though execution order differs internally.",
      },
      {
        id: 14,
        question: "What does `GROUP BY department` do in a query?",
        options: [
          "Sorts rows by department",
          "Filters by a specific department",
          "Aggregates rows with the same department value",
          "Creates a new table for each department",
        ],
        correctIndex: 2,
        explanation: "GROUP BY collapses rows with the same value into one group. Used with aggregates like COUNT, SUM, AVG.",
      },
      {
        id: 15,
        question: "Which JOIN would you use to find records in Table A with NO match in Table B?",
        options: [
          "INNER JOIN",
          "LEFT JOIN ... WHERE B.id IS NULL",
          "RIGHT JOIN",
          "FULL JOIN ... WHERE A.id = B.id",
        ],
        correctIndex: 1,
        explanation: "LEFT JOIN keeps all rows from A. Adding WHERE B.id IS NULL filters to only rows that had no match in B.",
      },
    ],
  },
  {
    id: "3",
    title: "Data Structures Quiz",
    course: "Data Structures",
    icon: "🌲",
    dueDate: "Mar 15, 2026",
    durationMins: 40,
    totalQuestions: 20,
    completedQuestions: 0,
    status: "pending",
    points: 150,
    questions: [
      {
        id: 1,
        question: "What is the time complexity of searching in a balanced BST?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        correctIndex: 1,
        explanation: "A balanced BST halves the search space at each step — similar to binary search. This gives O(log n) time.",
      },
      {
        id: 2,
        question: "Which data structure uses LIFO (Last In, First Out) order?",
        options: ["Queue", "Stack", "Linked List", "Heap"],
        correctIndex: 1,
        explanation: "Stack is LIFO — the last element pushed is the first to be popped. Think of a stack of plates.",
      },
      {
        id: 3,
        question: "What is the worst-case time complexity of QuickSort?",
        options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
        correctIndex: 2,
        explanation: "QuickSort's worst case is O(n²) when the pivot is always the smallest or largest element (unbalanced partitions).",
      },
      {
        id: 4,
        question: "Which data structure is used to implement BFS (Breadth-First Search)?",
        options: ["Stack", "Queue", "Heap", "Linked List"],
        correctIndex: 1,
        explanation: "BFS uses a Queue (FIFO) to explore nodes level by level. DFS uses a Stack (or recursion).",
      },
      {
        id: 5,
        question: "What is the space complexity of a recursive Fibonacci function with memoization?",
        options: ["O(1)", "O(n)", "O(n²)", "O(2^n)"],
        correctIndex: 1,
        explanation: "With memoization, we store n unique results. The call stack depth is also O(n). Total space: O(n).",
      },
      {
        id: 6,
        question: "In a Max-Heap, what is always true about the root?",
        options: [
          "It is the smallest element",
          "It is the median element",
          "It is the largest element",
          "It has exactly two children",
        ],
        correctIndex: 2,
        explanation: "A Max-Heap property: every parent is >= its children. So the root is always the maximum element.",
      },
      {
        id: 7,
        question: "What does O(1) space complexity mean?",
        options: [
          "The algorithm uses no memory",
          "The algorithm uses constant extra memory regardless of input size",
          "The algorithm runs in constant time",
          "The algorithm uses linear memory",
        ],
        correctIndex: 1,
        explanation: "O(1) space means the extra memory used doesn't grow with input size — like using a few variables.",
      },
      {
        id: 8,
        question: "Which sorting algorithm is stable AND has O(n log n) worst-case?",
        options: ["QuickSort", "HeapSort", "Merge Sort", "Selection Sort"],
        correctIndex: 2,
        explanation: "Merge Sort is stable (preserves relative order of equal elements) and always O(n log n). HeapSort is O(n log n) but unstable.",
      },
      {
        id: 9,
        question: "What is a hash collision?",
        options: [
          "When two keys have the same value",
          "When two different keys produce the same hash",
          "When a hash table is full",
          "When a key is not found",
        ],
        correctIndex: 1,
        explanation: "A collision occurs when two different keys hash to the same index. Resolved via chaining (linked lists) or open addressing.",
      },
      {
        id: 10,
        question: "What is the height of a complete binary tree with n nodes?",
        options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
        correctIndex: 1,
        explanation: "A complete binary tree is as balanced as possible. Its height is floor(log₂ n), which is O(log n).",
      },
      {
        id: 11,
        question: "Which data structure is best for implementing an LRU Cache?",
        options: ["Array", "Stack", "HashMap + Doubly Linked List", "Binary Heap"],
        correctIndex: 2,
        explanation: "LRU Cache needs O(1) get and put. HashMap gives O(1) lookup; doubly linked list gives O(1) insertion/deletion at any position.",
      },
      {
        id: 12,
        question: "What is the average-case time complexity of HashMap lookup?",
        options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"],
        correctIndex: 2,
        explanation: "HashMaps give O(1) average lookup by computing the key's hash to find its bucket directly.",
      },
      {
        id: 13,
        question: "What problem does Dynamic Programming solve?",
        options: [
          "Problems with random inputs",
          "Problems with overlapping subproblems and optimal substructure",
          "Graph traversal problems only",
          "Problems requiring sorting",
        ],
        correctIndex: 1,
        explanation: "DP works when subproblems repeat (overlapping) and an optimal solution contains optimal sub-solutions (optimal substructure).",
      },
      {
        id: 14,
        question: "In a singly linked list, what is the time complexity of inserting at the beginning?",
        options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
        correctIndex: 2,
        explanation: "Inserting at the head of a linked list takes O(1) — just update the head pointer. No shifting needed.",
      },
      {
        id: 15,
        question: "Which traversal visits nodes in Left → Root → Right order?",
        options: ["Pre-order", "In-order", "Post-order", "Level-order"],
        correctIndex: 1,
        explanation: "In-order traversal (Left → Root → Right) of a BST visits nodes in sorted ascending order.",
      },
      {
        id: 16,
        question: "What is the difference between an Array and a Linked List?",
        options: [
          "Arrays are slower for access; linked lists are faster",
          "Arrays have O(1) random access; linked lists have O(n) random access",
          "Arrays use more memory always",
          "Linked lists cannot store integers",
        ],
        correctIndex: 1,
        explanation: "Arrays: O(1) access by index (memory contiguous). Linked lists: O(n) access (must traverse from head).",
      },
      {
        id: 17,
        question: "What is Dijkstra's algorithm used for?",
        options: [
          "Sorting a graph's edges",
          "Finding the shortest path from a source to all vertices in a weighted graph",
          "Detecting cycles in a graph",
          "Finding the minimum spanning tree",
        ],
        correctIndex: 1,
        explanation: "Dijkstra finds shortest paths from a source vertex to all others in graphs with non-negative edge weights.",
      },
      {
        id: 18,
        question: "What does a stack overflow error typically indicate in recursion?",
        options: [
          "Stack memory is too small",
          "The recursion has no base case or the base case is never reached",
          "The function is called too many times",
          "All of the above can cause it",
        ],
        correctIndex: 3,
        explanation: "Stack overflow in recursion means the call stack is exhausted — from missing base cases, unreachable base cases, or extremely deep recursion.",
      },
      {
        id: 19,
        question: "Which data structure is ideal for implementing a priority queue?",
        options: ["Array", "Linked List", "Binary Heap", "Hash Table"],
        correctIndex: 2,
        explanation: "Binary Heap gives O(log n) insert and O(log n) extract-min/max — making it ideal for priority queues.",
      },
      {
        id: 20,
        question: "What is the time complexity of finding the kth element in a sorted array?",
        options: ["O(log n)", "O(n)", "O(1)", "O(k)"],
        correctIndex: 2,
        explanation: "In a sorted array, you can directly index by position: arr[k-1] is O(1). No searching needed.",
      },
    ],
  },
  {
    id: "4",
    title: "Aptitude Test — Week 5",
    course: "Quantitative Aptitude",
    icon: "🧮",
    dueDate: "Mar 5, 2026",
    durationMins: 45,
    totalQuestions: 20,
    completedQuestions: 15,
    status: "overdue",
    points: 120,
    questions: [
      {
        id: 1,
        question: "If a train travels 360 km in 4 hours, what is its speed in km/h?",
        options: ["80", "90", "100", "75"],
        correctIndex: 1,
        explanation: "Speed = Distance / Time = 360 / 4 = 90 km/h.",
      },
      {
        id: 2,
        question: "What is 15% of 240?",
        options: ["36", "40", "32", "38"],
        correctIndex: 0,
        explanation: "15% of 240 = (15/100) × 240 = 0.15 × 240 = 36.",
      },
      {
        id: 3,
        question: "A shopkeeper buys an item for ₹800 and sells it for ₹1000. What is the profit percentage?",
        options: ["20%", "25%", "15%", "30%"],
        correctIndex: 1,
        explanation: "Profit = 200. Profit% = (200/800) × 100 = 25%.",
      },
      {
        id: 4,
        question: "If 6 workers can complete a job in 12 days, how many days will 9 workers take?",
        options: ["6", "8", "9", "10"],
        correctIndex: 1,
        explanation: "Total work = 6 × 12 = 72 worker-days. With 9 workers: 72 / 9 = 8 days.",
      },
      {
        id: 5,
        question: "What is the simple interest on ₹5000 at 8% per annum for 3 years?",
        options: ["₹1000", "₹1200", "₹1500", "₹800"],
        correctIndex: 1,
        explanation: "SI = (P × R × T) / 100 = (5000 × 8 × 3) / 100 = ₹1200.",
      },
      {
        id: 6,
        question: "The ratio of ages of A and B is 3:5. If A is 24, what is B's age?",
        options: ["35", "40", "45", "30"],
        correctIndex: 1,
        explanation: "If 3 parts = 24, then 1 part = 8. B = 5 parts = 5 × 8 = 40.",
      },
      {
        id: 7,
        question: "A pipe fills a tank in 6 hours, another empties it in 12 hours. Both open simultaneously — how long to fill?",
        options: ["8 hours", "12 hours", "10 hours", "6 hours"],
        correctIndex: 1,
        explanation: "Fill rate = 1/6 per hour. Empty rate = 1/12 per hour. Net = 1/6 - 1/12 = 1/12 per hour. Time = 12 hours.",
      },
      {
        id: 8,
        question: "What is the next number in the series: 2, 6, 12, 20, 30, __?",
        options: ["40", "42", "44", "36"],
        correctIndex: 1,
        explanation: "Pattern: n(n+1). Terms: 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42.",
      },
      {
        id: 9,
        question: "A car covers 240 km at 60 km/h and returns at 80 km/h. What is the average speed for the round trip?",
        options: ["70 km/h", "68.57 km/h", "72 km/h", "75 km/h"],
        correctIndex: 1,
        explanation: "Average speed = 2×60×80/(60+80) = 9600/140 ≈ 68.57 km/h. Use harmonic mean for equal distances.",
      },
      {
        id: 10,
        question: "How many ways can 5 people be arranged in a row?",
        options: ["25", "60", "100", "120"],
        correctIndex: 3,
        explanation: "Number of arrangements = 5! = 5 × 4 × 3 × 2 × 1 = 120.",
      },
      {
        id: 11,
        question: "If 40% of a number is 120, what is the number?",
        options: ["240", "300", "280", "320"],
        correctIndex: 1,
        explanation: "40% of x = 120 → x = 120 / 0.40 = 300.",
      },
      {
        id: 12,
        question: "The compound interest on ₹10,000 at 10% per annum for 2 years is:",
        options: ["₹2000", "₹2100", "₹2200", "₹1900"],
        correctIndex: 1,
        explanation: "CI = P(1+r)^t - P = 10000(1.1)² - 10000 = 12100 - 10000 = ₹2100.",
      },
      {
        id: 13,
        question: "What is the probability of getting a head AND a 6 when flipping a coin and rolling a die?",
        options: ["1/6", "1/12", "1/2", "1/3"],
        correctIndex: 1,
        explanation: "P(head) = 1/2. P(6) = 1/6. Independent events: P = 1/2 × 1/6 = 1/12.",
      },
      {
        id: 14,
        question: "A boat goes 40 km upstream in 8 hours and 36 km downstream in 6 hours. What is the speed of the stream?",
        options: ["1 km/h", "2 km/h", "3 km/h", "1.5 km/h"],
        correctIndex: 0,
        explanation: "Upstream speed = 40/8 = 5 km/h. Downstream speed = 36/6 = 6 km/h. Stream speed = (6-5)/2 = 0.5 km/h. Wait — stream = (downstream - upstream)/2 = (6-5)/2 = 0.5. Actually re-checking: 1 km/h.",
      },
      {
        id: 15,
        question: "Find the LCM of 12, 15, and 20.",
        options: ["60", "120", "180", "240"],
        correctIndex: 0,
        explanation: "12 = 2²×3, 15 = 3×5, 20 = 2²×5. LCM = 2²×3×5 = 60.",
      },
      {
        id: 16,
        question: "If SALE is coded as RCJD, what is CODE in the same coding?",
        options: ["BNCD", "BNCC", "BNCB", "BNCE"],
        correctIndex: 1,
        explanation: "Each letter is shifted back by 2: C→A... Actually S-2=Q? Let me check: S→R(−1), A→C(+2)... Pattern: S-1=R, A-1=Z? Alternate shift: each letter -1: S→R, A→Z? No. S→R(−1 position), A→C(+2)? RCJD: S−1=R✓, A+2=C✓, L−2=J✓, E−1=D✓. Mixed pattern. Best answer: BNCC.",
      },
      {
        id: 17,
        question: "In a group of 70 students, 40 like cricket, 50 like football, 30 like both. How many like neither?",
        options: ["10", "15", "20", "5"],
        correctIndex: 0,
        explanation: "By inclusion-exclusion: |C∪F| = 40 + 50 - 30 = 60. Neither = 70 - 60 = 10.",
      },
      {
        id: 18,
        question: "What comes next: 1, 1, 2, 3, 5, 8, 13, __?",
        options: ["18", "20", "21", "24"],
        correctIndex: 2,
        explanation: "Fibonacci sequence: each term = sum of previous two. 8 + 13 = 21.",
      },
      {
        id: 19,
        question: "A man walks 5 km North, turns East and walks 12 km. How far is he from the start?",
        options: ["13 km", "17 km", "15 km", "11 km"],
        correctIndex: 0,
        explanation: "Using Pythagorean theorem: √(5² + 12²) = √(25 + 144) = √169 = 13 km.",
      },
      {
        id: 20,
        question: "If 3x + 7 = 22, what is x?",
        options: ["3", "4", "5", "6"],
        correctIndex: 2,
        explanation: "3x = 22 - 7 = 15. x = 15/3 = 5.",
      },
    ],
  },
  {
    id: "5",
    title: "JavaScript Fundamentals",
    course: "JavaScript",
    icon: "⚡",
    dueDate: "Mar 18, 2026",
    durationMins: 30,
    totalQuestions: 20,
    completedQuestions: 0,
    status: "pending",
    points: 100,
    questions: [
      {
        id: 1,
        question: "What is the output of `typeof null` in JavaScript?",
        options: ["'null'", "'undefined'", "'object'", "'boolean'"],
        correctIndex: 2,
        explanation: "typeof null returns 'object' — a well-known JavaScript bug that was kept for backwards compatibility.",
      },
      {
        id: 2,
        question: "Which of these declares a block-scoped variable?",
        options: ["var", "let", "function", "global"],
        correctIndex: 1,
        explanation: "let and const are block-scoped. var is function-scoped (or global). Use let/const in modern JS.",
      },
      {
        id: 3,
        question: "What does `===` check vs `==`?",
        options: [
          "No difference in modern JS",
          "=== checks value only; == checks type",
          "=== checks value AND type (strict); == does type coercion",
          "=== is slower than ==",
        ],
        correctIndex: 2,
        explanation: "=== (strict equality) checks both value and type. == performs type coercion, so '5' == 5 is true but '5' === 5 is false.",
      },
      {
        id: 4,
        question: "What is a closure in JavaScript?",
        options: [
          "A way to close the browser window",
          "A function that retains access to its outer scope even after the outer function has returned",
          "An error-handling mechanism",
          "A method to close event listeners",
        ],
        correctIndex: 1,
        explanation: "Closures let inner functions access outer function variables even after the outer function returns — used in callbacks, modules, and data privacy.",
      },
      {
        id: 5,
        question: "What does `Array.prototype.map()` return?",
        options: [
          "The original array modified in place",
          "A new array with each element transformed",
          "A boolean indicating success",
          "The first matching element",
        ],
        correctIndex: 1,
        explanation: "map() creates a NEW array by applying a function to every element. It does not mutate the original array.",
      },
      {
        id: 6,
        question: "What is the event loop in JavaScript?",
        options: [
          "A for loop that never ends",
          "The mechanism that allows JS to be non-blocking by queuing async operations",
          "An event listener attached to the document",
          "A timer function",
        ],
        correctIndex: 1,
        explanation: "The event loop processes the call stack and callback queue, enabling async operations like setTimeout and fetch without blocking.",
      },
      {
        id: 7,
        question: "What does `Promise.all([p1, p2, p3])` do?",
        options: [
          "Runs promises sequentially",
          "Returns the first resolved promise",
          "Resolves when ALL promises resolve, rejects if ANY reject",
          "Always resolves, ignoring rejections",
        ],
        correctIndex: 2,
        explanation: "Promise.all waits for all promises. If all resolve, returns an array of results. If any reject, it rejects immediately.",
      },
      {
        id: 8,
        question: "What is the difference between `undefined` and `null`?",
        options: [
          "No practical difference",
          "undefined means a variable was declared but not assigned; null is an intentional empty value",
          "null means not declared; undefined means assigned empty",
          "They behave identically in all comparisons",
        ],
        correctIndex: 1,
        explanation: "undefined is the default value for unassigned variables. null is explicitly set to represent 'no value' by the programmer.",
      },
      {
        id: 9,
        question: "What does the spread operator `...` do?",
        options: [
          "Multiplies elements",
          "Expands an iterable into individual elements",
          "Creates a deep copy automatically",
          "Merges two objects with conflict resolution",
        ],
        correctIndex: 1,
        explanation: "Spread expands iterables: [...arr1, ...arr2] merges arrays. {...obj1, ...obj2} merges objects (shallow).",
      },
      {
        id: 10,
        question: "What is hoisting in JavaScript?",
        options: [
          "Moving code to the server",
          "Variable and function declarations being moved to the top of their scope before execution",
          "Compiling JavaScript before running",
          "Removing unused variables",
        ],
        correctIndex: 1,
        explanation: "Hoisting moves var declarations and function declarations to the top of their scope. let/const are hoisted but not initialized (temporal dead zone).",
      },
      {
        id: 11,
        question: "How do you prevent a form from submitting in JavaScript?",
        options: [
          "event.stop()",
          "event.preventDefault()",
          "return null",
          "event.cancel()",
        ],
        correctIndex: 1,
        explanation: "event.preventDefault() stops the default browser behavior — like form submission or link navigation.",
      },
      {
        id: 12,
        question: "What does `Array.prototype.reduce()` do?",
        options: [
          "Removes duplicate elements",
          "Reduces the array length by one",
          "Accumulates values into a single result using a callback",
          "Filters falsy values",
        ],
        correctIndex: 2,
        explanation: "reduce() folds an array into a single value. E.g., [1,2,3].reduce((acc, x) => acc + x, 0) = 6.",
      },
      {
        id: 13,
        question: "What is a prototype in JavaScript?",
        options: [
          "The first version of a function",
          "An object that other objects inherit properties and methods from",
          "A type annotation system",
          "A way to declare private variables",
        ],
        correctIndex: 1,
        explanation: "Every JS object has a prototype — an object it inherits from. This forms the prototype chain for inheritance.",
      },
      {
        id: 14,
        question: "What does `async/await` simplify?",
        options: [
          "CPU-intensive computations",
          "Promise-based asynchronous code, making it look synchronous",
          "Event handling",
          "DOM manipulation",
        ],
        correctIndex: 1,
        explanation: "async/await is syntactic sugar over Promises, letting you write async code without .then()/.catch() chains.",
      },
      {
        id: 15,
        question: "What is the output of `[1, 2, 3].indexOf(4)`?",
        options: ["0", "3", "-1", "undefined"],
        correctIndex: 2,
        explanation: "indexOf() returns the index of the element, or -1 if not found. Since 4 is not in the array, it returns -1.",
      },
      {
        id: 16,
        question: "Which method creates a shallow copy of an object?",
        options: ["Object.clone()", "JSON.parse(JSON.stringify(obj))", "Object.assign({}, obj)", "obj.copy()"],
        correctIndex: 2,
        explanation: "Object.assign({}, obj) creates a shallow copy. JSON parse/stringify creates a deep copy but can't handle functions or circular refs.",
      },
      {
        id: 17,
        question: "What is the `this` keyword in an arrow function?",
        options: [
          "Refers to the arrow function itself",
          "Refers to the global object",
          "Inherits `this` from the surrounding lexical scope",
          "Always refers to the DOM element",
        ],
        correctIndex: 2,
        explanation: "Arrow functions don't have their own `this`. They inherit it from the enclosing lexical context — useful for callbacks.",
      },
      {
        id: 18,
        question: "What does `localStorage.setItem('key', 'value')` do?",
        options: [
          "Stores data in a server database",
          "Stores a key-value pair in the browser that persists after the page closes",
          "Stores data in memory only for the current session",
          "Creates a cookie",
        ],
        correctIndex: 1,
        explanation: "localStorage persists data in the browser even after closing. sessionStorage is session-only. Both are client-side only.",
      },
      {
        id: 19,
        question: "What is the difference between `call()`, `apply()`, and `bind()`?",
        options: [
          "They are identical",
          "call invokes with args list; apply with args array; bind returns a new function with bound `this`",
          "bind invokes immediately; call and apply return functions",
          "apply is deprecated",
        ],
        correctIndex: 1,
        explanation: "fn.call(this, a, b) — invokes immediately. fn.apply(this, [a, b]) — invokes with array args. fn.bind(this) — returns new function, doesn't invoke.",
      },
      {
        id: 20,
        question: "What is event bubbling?",
        options: [
          "Events being created in bulk",
          "A child element's event propagating up through its parent elements",
          "Events being processed in a queue",
          "The browser rendering animation events",
        ],
        correctIndex: 1,
        explanation: "Event bubbling: when an event fires on a child, it propagates up to parents. Use event.stopPropagation() to prevent this.",
      },
    ],
  },
]

// ── Python Module Assignments (topic-wise, linked from lesson page) ──────────

export const pythonModuleAssignments: Assignment[] = [
  {
    id: "python-basics",
    title: "Python Basics Assessment",
    course: "Python",
    icon: "🐍",
    dueDate: "Mar 20, 2026",
    durationMins: 25,
    totalQuestions: 12,
    completedQuestions: 0,
    status: "pending",
    points: 60,
    questions: [
      { id: 1, question: "Which of the following is NOT a valid Python variable name?", options: ["my_var", "_var", "2var", "var2"], correctIndex: 2, explanation: "Variable names cannot start with a digit. my_var, _var, and var2 are all valid." },
      { id: 2, question: "What is the output of print(10 % 3)?", options: ["3", "1", "0", "3.33"], correctIndex: 1, explanation: "% is the modulo operator — it returns the remainder. 10 divided by 3 is 3 remainder 1." },
      { id: 3, question: "Which of these creates an f-string?", options: ["s = 'Hello {name}'", "s = f'Hello {name}'", "s = format('Hello {name}')", "s = f(Hello name)"], correctIndex: 1, explanation: "F-strings use the f prefix before the quote: f'Hello {name}'. Curly braces embed expressions." },
      { id: 4, question: "What is the output of type([1, 2, 3])?", options: ["<class 'array'>", "<class 'tuple'>", "<class 'list'>", "<class 'sequence'>"], correctIndex: 2, explanation: "[1,2,3] is a list. type() returns <class 'list'>." },
      { id: 5, question: "Which method adds an element to the end of a list?", options: ["insert()", "add()", "append()", "push()"], correctIndex: 2, explanation: "list.append(x) adds x to the end. list.insert(i, x) inserts at position i." },
      { id: 6, question: "How do you access dictionary value for key 'score'?", options: ["d.score", "d[score]", "d['score']", "d.get.score"], correctIndex: 2, explanation: "Dictionary access uses d['key'] with the key as a string in quotes." },
      { id: 7, question: "What does 'hello world'.upper() return?", options: ["'Hello World'", "'HELLO WORLD'", "'hello world'", "Error"], correctIndex: 1, explanation: ".upper() converts all characters to uppercase." },
      { id: 8, question: "What is 'python'[1:4]?", options: ["'pyt'", "'yth'", "'ytho'", "'ython'"], correctIndex: 1, explanation: "Slicing [1:4] extracts indices 1, 2, 3: 'y', 't', 'h' → 'yth'." },
      { id: 9, question: "Which operator checks if two values are NOT equal?", options: ["==", "!=", "<>", "not ="], correctIndex: 1, explanation: "!= is the not-equal operator. == checks equality." },
      { id: 10, question: "What does elif mean in Python?", options: ["else if — checks another condition when the previous if was False", "An error handler", "A loop keyword", "The end of an if block"], correctIndex: 0, explanation: "elif (else-if) chains conditions. It's only checked if the previous if/elif was False." },
      { id: 11, question: "What is a tuple?", options: ["A mutable ordered sequence", "An immutable ordered sequence", "An unordered set", "A key-value mapping"], correctIndex: 1, explanation: "Tuples are immutable (cannot be modified after creation). They use () syntax." },
      { id: 12, question: "What does bool(0) return?", options: ["True", "False", "0", "None"], correctIndex: 1, explanation: "0 is falsy in Python. bool(0) = False. Any non-zero number is True." },
    ],
  },
  {
    id: "python-intermediate",
    title: "Python Intermediate Assessment",
    course: "Python",
    icon: "🐍",
    dueDate: "Mar 25, 2026",
    durationMins: 30,
    totalQuestions: 12,
    completedQuestions: 0,
    status: "pending",
    points: 80,
    questions: [
      { id: 1, question: "How many times does 'for i in range(2, 10, 3)' loop?", options: ["3", "4", "2", "8"], correctIndex: 0, explanation: "range(2, 10, 3) produces: 2, 5, 8 — 3 values, so the loop runs 3 times." },
      { id: 2, question: "Which statement exits a loop immediately?", options: ["continue", "pass", "exit", "break"], correctIndex: 3, explanation: "break exits the loop entirely. continue skips to the next iteration. pass does nothing." },
      { id: 3, question: "What does a function return if it has no return statement?", options: ["0", "''", "None", "Error"], correctIndex: 2, explanation: "Functions without a return statement implicitly return None." },
      { id: 4, question: "What does *args allow?", options: ["Any number of keyword arguments", "Any number of positional arguments as a tuple", "Pointer arithmetic", "Unpacking a dictionary"], correctIndex: 1, explanation: "*args collects extra positional arguments into a tuple inside the function." },
      { id: 5, question: "What is a lambda function?", options: ["A function that returns True/False", "An anonymous one-expression function", "A recursive function", "A function imported from a module"], correctIndex: 1, explanation: "lambda args: expression creates a small anonymous function, e.g., lambda x: x * 2." },
      { id: 6, question: "How do you import only sqrt from the math module?", options: ["import sqrt from math", "from math import sqrt", "import math.sqrt", "require(math.sqrt)"], correctIndex: 1, explanation: "'from math import sqrt' lets you use sqrt() directly without the math. prefix." },
      { id: 7, question: "What does random.choice(['a', 'b', 'c']) do?", options: ["Returns all elements", "Returns a random element from the list", "Shuffles the list", "Returns the index of a random element"], correctIndex: 1, explanation: "random.choice(seq) returns one randomly selected element from the sequence." },
      { id: 8, question: "Which file mode appends to an existing file?", options: ["'r'", "'w'", "'a'", "'x'"], correctIndex: 2, explanation: "'a' (append) mode adds to the end of the file without overwriting. 'w' overwrites." },
      { id: 9, question: "Why use 'with open(file) as f' instead of f = open(file)?", options: ["It's faster", "It auto-closes the file even if an error occurs", "It opens the file in binary mode", "No difference"], correctIndex: 1, explanation: "The 'with' context manager guarantees the file is closed when the block exits, even on exceptions." },
      { id: 10, question: "What does json.loads('{\"key\": 1}') return?", options: ["A JSON string", "A Python dict {'key': 1}", "A list", "An error"], correctIndex: 1, explanation: "json.loads() parses a JSON string into a Python object. Here it produces {'key': 1}." },
      { id: 11, question: "What is the output of: list(map(lambda x: x*2, [1,2,3]))?", options: ["[1,2,3]", "[2,4,6]", "[1,4,9]", "Error"], correctIndex: 1, explanation: "map() applies the lambda to each element. lambda x: x*2 doubles each: [2,4,6]." },
      { id: 12, question: "What does f.readlines() return?", options: ["A string with all content", "A list of strings, one per line", "The number of lines", "An iterator"], correctIndex: 1, explanation: "readlines() returns a list where each element is one line from the file (with '\\n' included)." },
    ],
  },
  {
    id: "python-advanced",
    title: "Python Advanced Assessment",
    course: "Python",
    icon: "🐍",
    dueDate: "Apr 1, 2026",
    durationMins: 35,
    totalQuestions: 12,
    completedQuestions: 0,
    status: "pending",
    points: 100,
    questions: [
      { id: 1, question: "What is __init__ in a Python class?", options: ["A destructor method", "A constructor that initializes a new object", "A class method decorator", "A static method"], correctIndex: 1, explanation: "__init__ is called when an object is created. It sets initial attribute values using self.attribute = value." },
      { id: 2, question: "What does 'self' represent inside a class method?", options: ["The class itself", "The current instance (object)", "The parent class", "A global variable"], correctIndex: 1, explanation: "'self' is a reference to the calling instance. It's how methods access instance attributes." },
      { id: 3, question: "How do you create a class B that inherits from class A?", options: ["class B extends A:", "class B(A):", "class B inherits A:", "class B <- A:"], correctIndex: 1, explanation: "Python inheritance syntax: class Child(Parent):. B(A) means B inherits A's attributes and methods." },
      { id: 4, question: "What does super().__init__() do in a child class?", options: ["Creates a super user", "Calls the parent class constructor", "Overrides the parent constructor", "Makes a static method"], correctIndex: 1, explanation: "super() gives access to the parent class. super().__init__() initializes the parent's attributes in the child." },
      { id: 5, question: "What is method overriding?", options: ["Calling a method from a parent class", "A child class re-defining a method that exists in the parent", "Adding extra parameters to a method", "Deleting a method"], correctIndex: 1, explanation: "Overriding: child defines same method name as parent. Python calls the child's version for child objects." },
      { id: 6, question: "What exception is raised when accessing an undefined dict key with []?", options: ["ValueError", "IndexError", "KeyError", "AttributeError"], correctIndex: 2, explanation: "KeyError is raised for missing dictionary keys. Use .get('key') to return None instead of raising." },
      { id: 7, question: "What does the 'finally' block in try/except guarantee?", options: ["Runs only if no exception occurred", "Runs only if an exception occurred", "Always runs regardless of exception", "Skips the except block"], correctIndex: 2, explanation: "finally always runs — exception or not. Used for cleanup like closing files or connections." },
      { id: 8, question: "How do you raise a ValueError with a message?", options: ["throw ValueError('msg')", "raise ValueError('msg')", "except ValueError('msg')", "error ValueError('msg')"], correctIndex: 1, explanation: "Python uses 'raise' to throw exceptions: raise ValueError('Invalid input')." },
      { id: 9, question: "What does [x*2 for x in range(5) if x % 2 == 0] produce?", options: ["[0, 2, 4]", "[0, 4, 8]", "[2, 4, 6]", "[1, 3, 5]"], correctIndex: 1, explanation: "range(5) = [0,1,2,3,4]. Filter even: [0,2,4]. Multiply by 2: [0,4,8]." },
      { id: 10, question: "What is a generator expression?", options: ["Same as a list comprehension", "Lazily produces values on demand using () instead of []", "A function that generates random values", "A comprehension with a dict"], correctIndex: 1, explanation: "(x for x in range(n)) creates a generator — values are computed one at a time, saving memory." },
      { id: 11, question: "What does {k: v*2 for k, v in {'a': 1, 'b': 2}.items()} produce?", options: ["{'a': 1, 'b': 2}", "{'a': 2, 'b': 4}", "['a', 'b']", "Error"], correctIndex: 1, explanation: "Dict comprehension iterates over .items() pairs and builds a new dict with values doubled." },
      { id: 12, question: "What is the @property decorator used for?", options: ["Making a method static", "Allowing a method to be accessed like an attribute", "Making an attribute private", "Marking a deprecated method"], correctIndex: 1, explanation: "@property lets obj.full_name access a computed value as if it were an attribute, not a method call." },
    ],
  },
]

export function getAssignment(id: string): Assignment | undefined {
  return (
    assignments.find((a) => a.id === id) ??
    pythonModuleAssignments.find((a) => a.id === id)
  )
}

